[PHP]
error_reporting = E_ALL
display_errors = On
log_errors = On
upload_max_filesize = 32M
post_max_size = 32M
memory_limit = 256M
max_execution_time = 60
date.timezone = "UTC"
default_charset = "UTF-8"

[opcache]
opcache.enable = 1
opcache.revalidate_freq = 0

[xdebug]
xdebug.mode = debug
xdebug.client_host = host.docker.internal
xdebug.client_port = 9003
